{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zitadel-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zitadel-operator.labels" . | nindent 4 }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
  - name: {{ if .Values.metrics.secure }}https{{ else }}http{{ end }}
    port: {{ .Values.metrics.service.port }}
    protocol: TCP
    targetPort: metrics
  selector:
    {{- include "zitadel-operator.selectorLabels" . | nindent 4 }}
{{- end }}
