{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "zitadel-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zitadel-operator.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - port: {{ if .Values.metrics.secure }}https{{ else }}http{{ end }}
    {{- if .Values.serviceMonitor.interval }}
    interval: {{ .Values.serviceMonitor.interval }}
    {{- end }}
    {{- if .Values.metrics.secure }}
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    {{- end }}
  selector:
    matchLabels:
      {{- include "zitadel-operator.selectorLabels" . | nindent 6 }}
{{- end }}
